### ISSUE TITLE
Seek does not trigger Traitors Quill

### ISSUE THREAD

**Issue by Ratvar** [Tempus/Disciple-Monster-Train#28] opened 2020-07-22 11:06 UTC
Seek, a consume spell, does not damage enemy with Traitors Quill artifact (deal 30 damage to front enemy unit when you play consume card) while showing it would in combat preview
![image](https://user-images.githubusercontent.com/22855970/88169359-8a55f700-cc24-11ea-8158-7181eb0b02aa.png)

**Comment by Tempus** [comment] 2020-07-23 08:01
This seems to occur with Divine cards as well. My belief is that the deck screen is overriding the subsequent actions somehow.

**Comment by RisingDusk** [comment] 2020-12-08 05:40
Closing as a duplicate of #126.

**Closed by RisingDusk** 2020-12-08 05:40 UTC
Labels: duplicate
